# Generated by Django 4.2.16 on 2024-11-11 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsabile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('qualifica', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Responsabile',
                'verbose_name_plural': 'Responsabili',
            },
        ),
        migrations.CreateModel(
            name='Struttura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('livello', models.CharField(choices=[('1', 'Ripartizioni/Staff'), ('2', 'Settore'), ('3', 'PoEQ')], max_length=1)),
                ('responsabile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strutture', to='organigramma.responsabile')),
                ('struttura_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sottostrutture', to='organigramma.struttura')),
            ],
            options={
                'verbose_name': 'Struttura',
                'verbose_name_plural': 'Strutture',
            },
        ),
    ]
