# Generated by Django 4.2.16 on 2024-11-11 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organigramma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Qualifica',
                'verbose_name_plural': 'Qualifiche',
            },
        ),
        migrations.AlterField(
            model_name='responsabile',
            name='qualifica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsabili', to='organigramma.qualifica'),
        ),
    ]
