# Generated by Django 4.2.16 on 2024-11-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramma', '0002_qualifica_alter_responsabile_qualifica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifica',
            name='titolo',
            field=models.CharField(max_length=100),
        ),
    ]
