# Generated by Django 4.2.16 on 2024-11-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramma', '0003_alter_qualifica_titolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='struttura',
            name='livello',
            field=models.CharField(choices=[('1', 'Ripartizioni/Staff'), ('2', 'Settore'), ('3', 'PoEQ'), ('4', 'Direzione')], max_length=1),
        ),
    ]
