# Generated by Django 4.2.16 on 2024-11-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramma', '0004_alter_struttura_livello'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifica',
            name='tipologia',
            field=models.CharField(choices=[('1', 'Amministrativo'), ('2', 'Tecnico'), ('3', 'Amministrativo contabile'), ('4', 'Specialista Amministrativo')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='responsabile',
            name='in_carica',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='qualifica',
            name='titolo',
            field=models.CharField(choices=[('1', 'Dirigente'), ('2', 'Funzionario')], max_length=100),
        ),
        migrations.AlterField(
            model_name='struttura',
            name='livello',
            field=models.CharField(choices=[('1', 'Direzione'), ('2', 'Ripartizioni/Staff'), ('3', 'Settori'), ('4', 'PoEQ')], max_length=1),
        ),
    ]
