# Generated by Django 4.2.16 on 2024-11-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramma', '0005_qualifica_tipologia_responsabile_in_carica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualifica',
            name='tipologia',
        ),
        migrations.AddField(
            model_name='qualifica',
            name='dirigente',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='qualifica',
            name='titolo',
            field=models.CharField(choices=[('1', 'Amministrativo'), ('2', 'Tecnico'), ('3', 'Amministrativo contabile'), ('4', 'Specialista Amministrativo')], max_length=100),
        ),
    ]
