# Generated by Django 4.2.16 on 2024-11-11 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organigramma', '0006_remove_qualifica_tipologia_qualifica_dirigente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsabile',
            name='data_fine',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responsabile',
            name='data_inizio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='struttura',
            name='data_fine',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='struttura',
            name='data_inizio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='qualifica',
            name='titolo',
            field=models.CharField(max_length=100),
        ),
    ]
