# Generated by Django 4.2.16 on 2024-11-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramma', '0007_responsabile_data_fine_responsabile_data_inizio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsabile',
            name='codice_fiscale',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='responsabile',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='struttura',
            name='livello',
            field=models.CharField(choices=[('1', 'Direzione'), ('2', 'Ripartizioni/Staff'), ('3', 'Settori'), ('4', 'PoEQ'), ('5', 'Avvocatura'), ('6', 'Sindaco')], max_length=1),
        ),
    ]
