# Generated by Django 4.2.16 on 2024-11-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramma', '0008_responsabile_codice_fiscale_responsabile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='struttura',
            name='livello',
            field=models.CharField(choices=[('1', 'Sindaco'), ('2', 'Giunta Comunale'), ('3', 'Direzione Generale'), ('4', 'Avvocatura'), ('5', 'Staff'), ('6', 'Ripartizioni'), ('7', 'Settore'), ('8', 'PoEQ'), ('9', 'Municipio')], max_length=1),
        ),
    ]
