# Generated by Django 4.2.16 on 2024-11-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramma', '0009_alter_struttura_livello'),
    ]

    operations = [
        migrations.AddField(
            model_name='struttura',
            name='codice',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
