# Generated by Django 4.2.16 on 2024-11-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramma', '0010_struttura_codice'),
    ]

    operations = [
        migrations.AddField(
            model_name='struttura',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='struttura',
            name='codice',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
