# Generated by Django 4.2.16 on 2024-11-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramma', '0011_struttura_url_alter_struttura_codice'),
    ]

    operations = [
        migrations.AddField(
            model_name='struttura',
            name='num_eng',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='struttura',
            name='num_ode',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='struttura',
            name='codice',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
