# Generated by Django 3.2.18 on 2024-11-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramma', '0012_struttura_num_eng_struttura_num_ode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsabile',
            name='codice_fiscale',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
