# Generated by Django 3.2.18 on 2024-11-26 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organigramma', '0013_alter_responsabile_codice_fiscale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Livello',
                'verbose_name_plural': 'Livelli',
            },
        ),
        migrations.AddField(
            model_name='struttura',
            name='historical_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='former_children', to='organigramma.struttura'),
        ),
        migrations.AlterField(
            model_name='struttura',
            name='livello',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strutture', to='organigramma.livello'),
        ),
    ]
