# Generated by Django 3.2.18 on 2025-08-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramma', '0014_auto_20241126_1655'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='struttura',
            index=models.Index(fields=['struttura_padre'], name='organigramm_struttu_2c2f36_idx'),
        ),
        migrations.AddIndex(
            model_name='struttura',
            index=models.Index(fields=['data_inizio', 'data_fine'], name='organigramm_data_in_3862c9_idx'),
        ),
    ]
