# Generated by Django 3.2.18 on 2025-08-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organigramma', '0015_auto_20250813_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='struttura',
            options={'ordering': ['codice'], 'verbose_name': 'Struttura', 'verbose_name_plural': 'Strutture'},
        ),
    ]
