# Generated by Django 3.2.18 on 2025-08-14 08:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organigramma', '0016_alter_struttura_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsabile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='struttura',
            name='responsabile',
            field=models.ForeignKey(blank=True, help_text="Campo non storico: mantenuto per retro-compatibilità. Per lo storico usare le 'Assegnazioni'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strutture', to='organigramma.responsabile'),
        ),
        migrations.CreateModel(
            name='StrutturaResponsabile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateField(default=django.utils.timezone.now)),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('responsabile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assegnazioni', to='organigramma.responsabile')),
                ('struttura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assegnazioni', to='organigramma.struttura')),
            ],
            options={
                'verbose_name': 'Assegnazione responsabile',
                'verbose_name_plural': 'Assegnazioni responsabili',
                'ordering': ['struttura', 'data_inizio'],
            },
        ),
        migrations.AddField(
            model_name='struttura',
            name='responsabili_storici',
            field=models.ManyToManyField(blank=True, related_name='strutture_storiche', through='organigramma.StrutturaResponsabile', to='organigramma.Responsabile'),
        ),
        migrations.AddIndex(
            model_name='strutturaresponsabile',
            index=models.Index(fields=['struttura', 'data_inizio', 'data_fine'], name='organigramm_struttu_eea2e2_idx'),
        ),
        migrations.AddIndex(
            model_name='strutturaresponsabile',
            index=models.Index(fields=['responsabile', 'data_inizio', 'data_fine'], name='organigramm_respons_cf59c6_idx'),
        ),
    ]
