# Generated by Django 3.2.18 on 2025-08-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigramma', '0017_auto_20250814_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livello',
            options={'ordering': ['ordine', 'nome'], 'verbose_name': 'Livello', 'verbose_name_plural': 'Livelli'},
        ),
        migrations.AddField(
            model_name='livello',
            name='can_be_root',
            field=models.BooleanField(default=True, help_text='Se disattivato, le strutture di questo livello DEVONO avere un padre.'),
        ),
        migrations.AddField(
            model_name='livello',
            name='ordine',
            field=models.PositiveIntegerField(default=0, help_text='Più basso = più in alto in gerarchia (es. Ente=0, Direzione=1, Servizio=2, ...)'),
        ),
    ]
