# Generated by Django 3.2.18 on 2025-08-14 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organigramma', '0018_auto_20250814_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='livello',
            name='allowed_parents',
            field=models.ManyToManyField(blank=True, help_text="Se valorizzato, il padre DEVE appartenere a uno di questi livelli. Se vuoto, si applica la regola d'ordine (padre.ordine < figlio.ordine).", related_name='allowed_children', to='organigramma.Livello'),
        ),
        migrations.AlterField(
            model_name='livello',
            name='ordine',
            field=models.PositiveIntegerField(default=0, help_text='0 = livello più alto (es. Ente=0, Direzione=1, Ripartizione=2, Settore=3, POEQ=4)'),
        ),
        migrations.AlterField(
            model_name='struttura',
            name='responsabile',
            field=models.ForeignKey(blank=True, help_text="Campo non storico: mantenuto per retro-compatibilità. Per lo storico usa le 'Assegnazioni'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strutture', to='organigramma.responsabile'),
        ),
    ]
